# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "sinatra", "~> 2.2"

gem "mongoid", "~> 7.0"

gem "jwt", "~> 2.2"
